# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(483, 285)
        mainWindow.setMinimumSize(QtCore.QSize(483, 285))
        mainWindow.setMaximumSize(QtCore.QSize(483, 285))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet("background-color: rgb(47, 44, 134);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 150, 141, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(74, 240, 255);\n"
"color: rgb(195, 23, 75);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 131, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 230, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 10, 191, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 70, 201, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 191, 51))
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 190, 141, 20))
        self.lineEdit_2.setStyleSheet("background-color: rgb(74, 240, 255);\n"
"color: rgb(195, 23, 75);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 131, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 230, 131, 21))
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 230, 141, 20))
        self.lineEdit_3.setStyleSheet("background-color: rgb(74, 240, 255);\n"
"color: rgb(195, 23, 75);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "FastBinder - by Yumix_"))
        self.label.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:26pt; color:#c3174b;\">FastBinder</span></p></body></html>"))
        self.label_2.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#c3174b;\">Клавиша бинда:</span></p></body></html>"))
        self.pushButton.setText(_translate("mainWindow", "Начинаем!"))
        self.label_3.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:26pt; color:#c3174b;\">By Yumix_</span></p></body></html>"))
        self.label_4.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:26pt; color:#c3174b;\">t.me/tem1b</span></p></body></html>"))
        self.label_5.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:26pt; color:#c3174b;\">qeo.su/fb</span></p></body></html>"))
        self.label_6.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#c3174b;\">Команда бинда:</span></p></body></html>"))
        self.label_7.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#c3174b;\">Клавиша чата: </span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
